Exam CSI-2 2020
mpgn/astudiaeth pull request #46
Opened 2020-12-17 16:51 UTC by ataumo

Effectivement, j'ai fait un peu n'importe quoi avant. J'espère que la ça va fonctionner.

2020-12-17 17:33 UTC, Pamplemousse requested changes
Quelques remarques :
  * `Master_CSI-S7/Arithmétique/Devoirs/dsarith2019.pdf` est déjà présent dans ce repo. Si c'est nécessaire de le mettre à jour, pourrais-tu expliquer pourquoi dans le message de commit ?
  * Décidément, ces `.DS_Store` se glissent partout ! Peux-tu les enlever STP ?

2020-12-17 17:53 UTC, ataumo commented
Je crois que c'est bon pour les `.DS_Stores`. Concernant `Master_CSI-S7/Arithmétique/Devoirs/dsarith2019.pdf` il est effectivement pas nécessaire de le mettre à jour.

2020-12-17 18:24 UTC, mpgn commented
je te laisse review et merge @Pamplemousse :)

C'est une très belle PR @ataumo encore merci 🥇

2020-12-17 19:47 UTC, Pamplemousse approved these changes

2020-12-17 19:47 UTC, merged

2020-12-17 19:53 UTC, Pamplemousse commented
Merci @ataumo !

Pense à "pull" avant la prochaine ;)
  * Astuce :
  `git pull` = `git fetch` + `git merge` et ça donne pas un historique très propre (ça crée un "merge commit"), du coup, c'est souvent d'usage de faire un `git pull --rebase` (qui équivaut à un `git fetch` + `git rebase`)
  * Astuce 2 :
  `git rebase -i` permet de faire un `rebase` interactif (choisir, supprimer, éditer des commits). Pratique pour clarifier l'historique (notamment pour lors de la soumission de PRs).

2020-12-18 22:55 UTC, ataumo commented
Avec plaisir !

Ok ! merci pour les conseils ! j'ai pas trop l'habitude de manipuler git ;)